services:
  - type: web
    name: lumos-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: lumos_bot
      - key: CHECK_INTERVAL
        value: 45
      - key: APQE_PQFRTY
        sync: false
      - key: APSRC_PFRTY
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /health
